 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/day_types", type: :request do
  # DayType. As you add validations to DayType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      DayType.create! valid_attributes
      get day_types_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      day_type = DayType.create! valid_attributes
      get day_type_url(day_type)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_day_type_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      day_type = DayType.create! valid_attributes
      get edit_day_type_url(day_type)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new DayType" do
        expect {
          post day_types_url, params: { day_type: valid_attributes }
        }.to change(DayType, :count).by(1)
      end

      it "redirects to the created day_type" do
        post day_types_url, params: { day_type: valid_attributes }
        expect(response).to redirect_to(day_type_url(DayType.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new DayType" do
        expect {
          post day_types_url, params: { day_type: invalid_attributes }
        }.to change(DayType, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post day_types_url, params: { day_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested day_type" do
        day_type = DayType.create! valid_attributes
        patch day_type_url(day_type), params: { day_type: new_attributes }
        day_type.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the day_type" do
        day_type = DayType.create! valid_attributes
        patch day_type_url(day_type), params: { day_type: new_attributes }
        day_type.reload
        expect(response).to redirect_to(day_type_url(day_type))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        day_type = DayType.create! valid_attributes
        patch day_type_url(day_type), params: { day_type: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested day_type" do
      day_type = DayType.create! valid_attributes
      expect {
        delete day_type_url(day_type)
      }.to change(DayType, :count).by(-1)
    end

    it "redirects to the day_types list" do
      day_type = DayType.create! valid_attributes
      delete day_type_url(day_type)
      expect(response).to redirect_to(day_types_url)
    end
  end
end
