 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/org_units", type: :request do
  # OrgUnit. As you add validations to OrgUnit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      OrgUnit.create! valid_attributes
      get org_units_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      org_unit = OrgUnit.create! valid_attributes
      get org_unit_url(org_unit)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_org_unit_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      org_unit = OrgUnit.create! valid_attributes
      get edit_org_unit_url(org_unit)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OrgUnit" do
        expect {
          post org_units_url, params: { org_unit: valid_attributes }
        }.to change(OrgUnit, :count).by(1)
      end

      it "redirects to the created org_unit" do
        post org_units_url, params: { org_unit: valid_attributes }
        expect(response).to redirect_to(org_unit_url(OrgUnit.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OrgUnit" do
        expect {
          post org_units_url, params: { org_unit: invalid_attributes }
        }.to change(OrgUnit, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post org_units_url, params: { org_unit: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested org_unit" do
        org_unit = OrgUnit.create! valid_attributes
        patch org_unit_url(org_unit), params: { org_unit: new_attributes }
        org_unit.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the org_unit" do
        org_unit = OrgUnit.create! valid_attributes
        patch org_unit_url(org_unit), params: { org_unit: new_attributes }
        org_unit.reload
        expect(response).to redirect_to(org_unit_url(org_unit))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        org_unit = OrgUnit.create! valid_attributes
        patch org_unit_url(org_unit), params: { org_unit: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested org_unit" do
      org_unit = OrgUnit.create! valid_attributes
      expect {
        delete org_unit_url(org_unit)
      }.to change(OrgUnit, :count).by(-1)
    end

    it "redirects to the org_units list" do
      org_unit = OrgUnit.create! valid_attributes
      delete org_unit_url(org_unit)
      expect(response).to redirect_to(org_units_url)
    end
  end
end
