== Setup der Datenbank

=== Die Rails-Konfigurationsdatei `database.yml`

Die Rails-seitige Konfiguration der Datenbank besteht aus einer
YAML-Datei, die Einträge für jede Umgebung enthält 
(Environment: `production`, `development`, `test`). 
Für die Produktivumgebung wird nur `production` benötigt, 
für eine Entwicklungsumgebung nur `development` und `test`.

Die Konfiguration ist abhängig vom Datenbanktreiber (`adapter`)
und wird hier beschrieben für MySQL/MariaDB. Für andere Datenbanken bitte
in der Rails-Dokumentation nachsehen.footnote:[http://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters.html]

[[database.yml]]
.database.yml
[source]
----
# -- mysql2
production:
  adapter: mysql2 <!--1-->
  encoding: utf8
  database: titracka_production <!--2-->
  pool: 5
  username: ###PLEASE_EDIT###  <!--3-->
  password: ###PLEASE_EDIT###  <!--4-->
  socket: /var/run/mysql/mysql.sock <!--5-->
  # host:  localhost # alternativ zu <5>
----
<1> gilt auch für MariaDB
<2> Name der Datenbank. Zur besseren Unterscheidung sollte man immer
    <name>_<environment> verwenden
<3> Username für den Datenbankzugriff
<4> Passwort für den Datenbankzugriff
<5> Abhängig von der Datenbankkonfiguration wahlweise über IP/Host oder UNIX-Socket.

