== Setup

=== Installation benötigter Pakete

[[packages-debian]]
.Pakete für Debian/Ubuntu
[source]
----
# base packages
apt install bzip2 curl screen vim vim-common vim-rails \
  wget pwgen sudo etckeeper ldap-client p7zip-full gdebi aptitude

# net packages
apt install bridge-utils ethtool tcpdump vlan mtr-tiny

# daemons
apt install ntp xinetd

# mail
apt install postfix mutt bsd-mailx

# development
apt install autoconf binutils bison build-essential flex gettext ncurses-dev

# database
apt install postgresql postgresql-client postgresql-common postgresql-contrib

# webserver
apt install apache2 apache2-bin apache2-data apache2-utils
apt install libapache2-mod-passenger

# ruby
apt install ruby ruby-bundler ruby-dev

# wobrailsapps
apt install libxml2 libxml2-dev zlib1g zlib1g-dev
apt install nodejs
# für closure; should be replaced!
apt install openjdk-9-jre-headless
----

==== Yarn für das Deployment von Javascript

[[yarn-packages-debian]]
.Pakete für Debian/Ubuntu
[source]
----
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install yarn
----

[[yarn-packages-fedora]]
.Pakete für Fedora
[source]
----
sudo wget https://dl.yarnpkg.com/rpm/yarn.repo -O /etc/yum.repos.d/yarn.repo
curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
dnf install -y yarn
----

=== User `deploy`

Die Installation der Anwendung erfolgt unter dem User `deploy`. Bei der
Installation und bei Updates werden Pakete aus dem Internet gezogen. In
durch einen Proxy geschützten Netzwerken setzt man die Variablen
`http_proxy` und `https_proxy` (`.bashrc`). Git greift nicht auf
die Shellvariablen zu, sondern benötigt eine eigene Konfiguration.

[[bashrc-deploy]]
.bashrc: Proxy-Einstellungen
[source]
----
export http_proxy=http://<proxy>:<proxyport>/
export https_proxy=http://<proxy>:<proxyport>/
----

[[git-config]]
.Git-Konfiguration User `deploy` für Updates der Anwendung
[source]
----
git config --global http.proxy http://<proxy>:<proxyport>/
git config --global https.proxy http://<proxy>:<proxyport>/
----

=== Verzeichnisse für Titracka

Vor dem ersten Deploy legt man die im Listing <<deployment-directories>>
angegebenen Verzeichnisse an. Die Verzeichnisse müssen alle
dem User `deploy` gehören.

[[deployment-directories]]
.Verzeichnisse für Titracka
[source]
----
export BASE=/srv/www/titracka
mkdir -p ${BASE}/titracka/releases
mkdir -p ${BASE}/titracka/shared/config
mkdir -p ${BASE}/titracka/shared/log
mkdir -p ${BASE}/titracka/shared/files
mkdir -p ${BASE}/titracka/shared/public/images
mkdir -p ${BASE}/titracka/shared/Backup/models
mkdir -p ${BASE}/titracka/shared/pids
chown deploy:deploy -R ${BASE}/titracka
----

[horizontal]
`./releases/`::
  Verzeichnis für die Installation des Codes. Normalerweise befinden
  sich hier die 5 letzten Updates, um bei Bedarf einen Rollback durchführen
  zu können. Ältere Versionen werden beim Deployment automatisch gelöscht.
`./current/`::
  Ein Symlink auf das jeweils aktuelle Release.
`./shared/`::
  Zentrales Verzeichnis für die statische Konfiguration und alle Dateien,
  die bei Updates der Anwendung unverändert bleiben.
`./shared/config/`::
  Konfigurationsdateien `application.yml`, `database.yml` und `secrets.yml` footnote:[secrets.yml ab ab Rails 4.2]
`./shared/log/`::
  Logdateien
`./shared/files/`::
  Dateiablage für Anlagen
`./shared/images/`::
  Dateiablage für Logos zu den OUs
`./shared/Backup/`::
  Konfigurationdateien für die Anwendungssicherung
`./shared/pids/`::
  wird von `delayed_job` für die Hintergrund-Jobs benötigt
