== Setup der Datenbank

=== Die Rails-Konfigurationsdatei `database.yml`

Die Rails-seitige Konfiguration der Datenbank besteht aus einer
YAML-Datei, die Einträge für jede Umgebung enthält 
(Environment: `production`, `development`, `test`). 
Für die Produktivumgebung wird nur `production` benötigt, 
für eine Entwicklungsumgebung nur `development` und `test`.

IMPORTANT: Titracka nutzt für Queries PostgreSQL-spezifische Statements. Bei der Nutzung einer anderen Datenbank sind nicht alle Funktionen nutzbar.

[[database.yml]]
.database.yml
[source]
----
# -- pgsql
production:
  adapter: postgresql <!--1-->
  encoding: unicode
  database: titracka_production <!--2-->
  pool: 5
  username: ###PLEASE_EDIT###  <!--3-->
  password: ###PLEASE_EDIT###  <!--4-->
  # host:  localhost <!--5-->
  # socket: ... # alternativ zu <!--5-->
 
----
<1> pgsql gem
<2> Name der Datenbank. Zur besseren Unterscheidung sollte man immer
    <name>_<environment> verwenden
<3> Username für den Datenbankzugriff
<4> Passwort für den Datenbankzugriff
<5> Abhängig von der Datenbankkonfiguration wahlweise über IP/Host oder UNIX-Socket.

